---
title: "Draft"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
library(ggcpesrthemes)
library(cowplot)
library(lubridate)


source("R/legiplot_fun_load.R")
lp_modifs <- legiplot_load_csv("data/lp_diff_t.csv")
lp_stats <- legiplot_load_csv("data/lp_diffstats_ts3.csv")

mandats <- read.csv("data/elections.csv") %>% 
  mutate(
    date = as.Date(date),
    président = factor(président, levels=unique(président)) )

lecode = "code de l'éducation"
startdate = as.Date("2017-06-01")

theme_cpesr_setup(authors = "Julien Gossa", source="https://github.com/juliengossa/legiplot")
```

```{r data}
lp_stats <- lp_stats %>%
  mutate(mandat = cut(date, method = "fixed", breaks = mandats$date, labels=head(mandats$président,-1)))
```


```{r check}
lp_modifs %>%
  filter(code == lecode) %>%
  filter(date >= startdate) %>%
  group_by(partie,sous_partie,article,type) %>%
  summarise(nb = n()) %>%
  arrange(desc(nb)) %>%
  head() %>%
  kableExtra::kable()
```


```{r check.2}
lp_modifs %>%
  filter(code == lecode) %>%
  filter(date >= startdate) %>%
  arrange(date) %>%
  group_by(article) %>%
  slice_head() %>% 
  group_by(partie,type) %>%
  summarise(nb = n()) %>%
  kableExtra::kable()
```


```{r check.3}
lp_modifs %>%
  filter(code == lecode) %>%
  filter(date >= startdate) %>%
  arrange(date) %>%
  group_by(article) %>%
  slice_head() %>% 
  group_by(type) %>%
  #group_by(partie,type) %>%
  summarise(nb = n()) %>%
  head() %>%
  kableExtra::kable()
```


```{r check.4}
lp_modifs %>%
  filter(code == lecode) %>%
  filter(date >= startdate) %>%
  arrange(date) %>%
  group_by(article) %>%
  slice_head() %>% 
  group_by(date) %>%
  summarise(nb = n()) %>%
  arrange(desc(nb)) %>%
  head() %>%
  kableExtra::kable() 
```




```{r code, fig.asp=9/16}

left_join(
  lp_modifs %>%
    filter(code == lecode) %>%
    filter(date >= startdate) %>%
    arrange(date) %>%
    group_by(article) %>%
    slice_head() %>% 
    group_by(date,partie,type) %>%
    summarise(nb = n()) %>%
    pivot_wider(names_from = type, values_from = nb, values_fill = c(nb=0))
  ,
  lps <- lp_stats %>%
    filter(code == lecode) %>%
    filter(date >= startdate) %>%
    group_by(date,partie) %>%
    summarise(nb_articles = sum(nb_articles)) 
) %>%
  group_by(partie) %>%
  arrange(date) %>%
  mutate(across(c(Modification,Ajout,Suppression), cumsum)) %>%
  mutate(Conservation = nb_articles - Ajout - Modification) %>%
  pivot_longer(
    c(Modification,Ajout,Suppression,Conservation),
    names_to = "Articles",
    values_to = "Nombre"
  ) %>% 
  mutate(Articles = factor(Articles,
    levels = c("Conservation","Modification","Ajout","Suppression"),
    labels = c("Conservés","Modifiés","Ajoutés","Supprimés")
  )) %>% 
  
  ggplot(aes(x=date,y=Nombre,color=Articles,fill=Articles)) +
    geom_area(aes(group=Articles), position="fill") +
    scale_color_brewer(palette = "Paired") +
    scale_fill_brewer(palette = "Paired") +
    scale_y_continuous(labels = scales::percent) +
    ylab("Proportion des articles") +
    facet_grid(.~partie) +
    ggtitle("Modifications du code de l'éducation sous la présidence d'E. Macron") +
    theme_cpesr_cap()

```




## Jumps

```{r load.jumps}
lpm <- legiplot_load_csv("data/lp_diffstats_jts5.csv") %>%
  group_by(code,date,partie) %>%
  summarise(across(starts_with("nb"),sum)) %>%
  mutate(fin = str_sub(date,1,4)) %>%
  left_join(
    left_join(
      tibble(fin=as.character(seq(1800,2022))),
      mandats %>% 
        mutate(fin=str_sub(lead(date),1,4)) %>% 
        select(-date) ) %>%
      fill(président, .direction="up")
    ) %>%
  mutate(nb_conservations = nb_articles - nb_modifications - nb_ajouts)


lpm.pivot <- lpm %>%
  pivot_longer(c(nb_modifications:nb_suppressions, nb_conservations),
               names_to = "modification", values_to = "articles", names_prefix = "nb_") %>%
  mutate(modification = factor(modification, 
                               levels = c("conservations","modifications","suppressions","ajouts"),
                               labels = c("Conservé","Modifié","Supprimé","Ajouté"))) %>%
  mutate(modification = fct_rev(modification)) %>%
  group_by(code,partie,modification) %>%
  mutate(ratio = articles / lag(nb_articles))
```

```{r check.jumps}
lpm %>%
  group_by(code,partie) %>%
  mutate(check = (nb_articles - (lag(nb_articles) + nb_ajouts - nb_suppressions))) %>%
  filter(check !=0 ) %>% 
  kableExtra::kable()
```


## Code de l'éducation

```{r education, fig.asp=9/16, fig.retina=2}
lpm.pivot %>%
  mutate(articles = ifelse(modification=="Supprimé",-articles,articles)) %>%
  filter(code == "code de l'éducation", partie == "Législative") %>%
  ggplot(aes(x=président,y=articles,fill=modification)) +
    geom_col(color="white", aes(group=modification)) +
    scale_fill_brewer(palette = "Paired", direction = -1, name="Article") +
    xlab("Présidence") + ylab("Nombre d'articles") +
    ggtitle("Modification des articles du Code de l'éducation (partie législative)") +
    theme_cpesr_cap()

```

```{r education.facet}
lpm.pivot %>%
  mutate(articles = ifelse(modification=="Supprimé",-articles,articles)) %>%
  filter(code == "code de l'éducation") %>%
  ggplot(aes(x=président,y=articles,fill=modification)) +
    geom_col() +
    facet_grid(partie~., scales = "free_y") +
    theme_cpesr_cap()

```
 
## Tous les codes dernier mandat

```{r touscodes, fig.width=8, fig.height=8}
lpm.pivot %>%
  filter(partie=="Législative" | code %in% c("code civil", "code de procédure civile")) %>%
  filter(président == "Macron") %>%
  ggplot(aes(x=reorder(code,articles,FUN=sum),y=articles,fill=modification)) +
    geom_col() +
    coord_flip() +
    theme_cpesr_cap()
```

```{r touscodes.ratio, fig.width=8, fig.height=8}
lpm.pivot %>%
  filter(partie=="Législative" | code %in% c("code civil", "code de procédure civile")) %>%
  filter(président == "Macron") %>%
  ggplot(aes(x=reorder(code,ratio,FUN=sum),y=ratio,fill=modification)) +
    geom_col() +
    coord_flip(ylim=c(0,1)) +
    theme_cpesr_cap()
```

```{r touscodes.ratio.2, fig.width=8, fig.asp=1/1}
lpm.sum <- lpm.pivot %>%
  filter(partie=="Législative" | code %in% c("code civil", "code de procédure civile")) %>%
  filter(président %in% c("Chirac 2","Sarkozy","Hollande")) %>%
  group_by(code,président,partie) %>%
  summarise(ratio = sum(ratio))

lpm.pivot %>%
  filter(partie=="Législative" | code %in% c("code civil", "code de procédure civile")) %>%
  filter(président == "Macron") %>%
  ggplot(aes(x=reorder(code,ratio,FUN=sum),y=ratio)) +
    geom_col(aes(fill=modification)) +
    geom_point(data=lpm.sum, aes(shape=président)) +
    coord_flip(ylim=c(0,1)) +
    scale_y_continuous(labels = scales::percent) +
    scale_shape(name="") +
    scale_fill_discrete(name="") +
    ggtitle("Proportion, par code, des articles modifiés durant le mandat de M. Macron", subtitle = "Partie législative seulement") +
    theme_cpesr_cap() +
    theme(legend.justification = "right",
          axis.title.x = element_blank(),
          axis.title.y = element_blank(),
          plot.title = element_text(hjust = 1)
      ) 
```


```{r touscodes.ratio.3, fig.width=10, fig.asp=2/1}
lpm.pivot %>%
  filter(partie=="Législative" | code %in% c("code civil", "code de procédure civile")) %>%
  filter(président %in% c("Chirac","Chirac 2","Sarkozy","Hollande","Macron")) %>%
  ggplot(aes(x=président,y=ratio)) +
    geom_col(aes(fill=modification)) +
    facet_wrap(code~., ncol=4, labeller = labeller(code=label_wrap_gen(34))) +
    scale_y_continuous(labels = scales::percent) +
    scale_shape(name="") +
    scale_fill_discrete(name="") +
    ggtitle("Proportion, par code, des articles modifiés durant le mandat de M. Macron", subtitle = "Partie législative seulement") +
    theme_cpesr_cap() +
    theme(legend.justification = "right",
          axis.title.x = element_blank(),
          axis.title.y = element_blank(),
          plot.title = element_text(hjust = 1),
          axis.text.x = element_text(angle=45,hjust=1)
      ) 
```


## Tous les codes tous les mandats

```{r tous.data, fig.width=8, fig.height=8}
lpm %>%
  filter(partie == "Législative") %>%
  mutate(
    Modifiés = nb_modifications,
    Ajoutés = nb_modifications + nb_ajouts,
    Supprimés = nb_modifications + nb_ajouts + nb_suppressions
  ) %>%
  pivot_longer(Modifiés:Supprimés, names_to = "Modification", values_to = "Articles") %>%
  mutate(Modification = factor(Modification, levels=rev(c("Modifiés","Ajoutés","Supprimés")))) %>%
  arrange(Modification) %>%
  ggplot(aes(x=président,y=reorder(code,Articles,FUN=sum), size=Articles, color=Modification)) + 
    geom_point() +
    scale_x_discrete(name="") +
    scale_y_discrete(name="") +
    scale_color_discrete(name="") +
    scale_size(name="") +
    #guides(color = guide_legend(direction="vertical", title=NULL)) +
    theme_cpesr_cap() +
    theme(axis.text.x = element_text(angle=45, hjust=1),
          legend.justification = "right")
```



## Waffles

```{r scolarite}
niveaux <- c("Maternelle PS", "Maternelle GS", "CP", "CE1", "CE2", "CM1", "CM2", "6ème", "5ème", "4ème", "3ème", "Seconde", "Première", "Terminale")
trimestres = c("1er trimestre", "2ème trimestre", "3ème trimestre","grandes vacances")
niveaux <- factor(niveaux,levels=niveaux)
trimestres <- factor(trimestres,levels=trimestres)

scolarite <- function(from="2009-09-01") {
  d <- as.Date(from)
  crossing(niveaux,trimestres) %>%
    mutate(label = paste(niveaux,trimestres,sep=" - ")) %>%
    mutate(date = d %m+% months(3*(row_number()-1)))
}  
scolarite()
```

```{r waffle, fig.asp=1}
waffle.data <- function(lecode="code de l'éducation",
                         from="2017-06-01", to="2023-06-01") {
  lp_modifs %>%
    filter(code == lecode, date < to) %>%
    slice_tail(n=1,by = article) %>%
    filter(type != "Suppression" | date >= from) %>%
    mutate(type = case_when(
      date < from & type == "Suppression" ~ "FAIL",
      date < from ~ "Conservé",
      type == "Préexistence" ~ "Conservé",
      type == "Modification" ~ "Modifié",
      type == "Ajout" ~ "Ajouté",
      type == "Suppression" ~ "Supprimé")) %>%
    mutate(type = factor(type,levels=c("Conservé","Modifié","Ajouté","Supprimé"))) 
}

waffle <- function(lecode="code de l'éducation",
                         from="2017-06-01", to="2023-06-01",
                         width=100, height=0, addtitle="") {
  df <- waffle.data(lecode,from,to)
  
  stats <- df %>% 
    summarise(nb = n(), .by = type) %>%
    complete(type, fill=list(nb = 0)) %>%
    mutate(part = nb / sum(nb)) %>%
    mutate(label = scales::percent(part,accuracy=1))
  
  statslab <- stats$label
  names(statslab) <- stats$type
  
  #return(stats)
    
  df %>%
    mutate(x = (row_number()-1) %% width, y = floor((row_number()-1) / width)) %>%
    ggplot(aes(x=x,y=y,fill=type)) +
    geom_tile(width=1,height=1, color="black") +
    expand_limits(y=height) +
    scale_y_reverse() +
    scale_fill_manual(values=c("aquamarine","darkorange","darkorchid1","deepskyblue"),
                      limits = c("Conservé","Modifié","Ajouté","Supprimé"),
                      name="Article") +
    theme_void() +
    theme(legend.position = "top", 
          plot.title = element_text(hjust=0.5), plot.subtitle = element_text(hjust=0.5),
          legend.margin=margin(t=0.5, b=0, unit='cm'),
          plot.margin=margin(t=0.3, b=0, unit='cm')) +
    labs(title = paste("Articles du",lecode,"entre",from,"et",to,addtitle),
            subtitle = paste("Conservés : ",statslab[['Conservé']],
                             ", Modifiés : ",statslab[['Modifié']],
                             ", Ajoutés : ",statslab[['Ajouté']],
                             ", Supprimés : ",statslab[['Supprimé']]),
            caption = "Julien Gossa, Camille Noûs, CPESR  |  Source : Légifrance via ArcheoLex  ")
}

waffle()
waffle(to="2017-06-01")
```


```{r waffgif, fig.asp=9/16}
waffle.pngs <- function(lecode="code de l'éducation",
                        from="2017-06-01", to="2023-06-01", 
                        width=100, height=0, delay=1, pause=3,
                        keeppng=FALSE) {
  dir.create("pngs")
  d <- as.Date(from)
  pngs <- c()
  while(d <= to) {
    print(d)
    fn <- paste0("pngs/waffle-",d,".png")
    if(!keeppng) {
      p <- waffle(lecode,from=from,to=d,width=width,height=height)
      ggsave(p, filename=fn, bg="white", width = 6, height = 6)
    }
    pngs <- c(pngs,fn)
    #d <- d %m+% months(12)
    d <- d %m+% months(1)
  }
  pngs <- c(rep(pngs[1],pause),pngs,rep(pngs[length(pngs)],pause))
  gifski::gifski(pngs,paste0(lecode,".gif"),width = 800, height = 800, delay = delay)
}

waffle.pngs(from="2017-06-01", to="2023-06-01", width=100, height=57, delay = 0.25, pause=10, keeppng = FALSE)
```



```{r waffscol, fig.asp=9/16}
waffle.scol <- function(width=100, height=0, delay=1, pause=3,
                        keeppng=FALSE) {
  lecode <- "code de l'éducation"
  dir.create("pngs")
  scol <- scolarite()
  pngs <- c()
  
  from <- scol[1,]$date
  for(i in 1:nrow(scol)) { 
    niv <- scol[i,]$label
    to <- scol[i,]$date
    fn <- paste0("pngs/scol-",to,".png")
    print(niv)
    if(!keeppng) {
      p <- waffle(lecode,from=from,to=to,width=width,height=height,addtitle=paste0("\n",niv))
      ggsave(p, filename=fn, bg="white", width = 6, height = 6)
    }
    pngs <- c(pngs,fn)
  }
  pngs <- c(rep(pngs[1],pause),pngs,rep(pngs[length(pngs)],pause))
  gifski::gifski(pngs,paste0("scolarite.gif"),width = 800, height = 800, delay = delay)
}

waffle.scol(width=100, height=60, delay = 0.25, pause=10, keeppng = FALSE)
```